# fly.toml app configuration file generated for backend-production-ogog on 2025-04-21T01:32:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-production-ogog'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  max_machines_count = 1
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 4

[env]
  ENV_MODE = "production"
